### ISSUE TITLE
[GTPU] GTP-U support 

### ISSUE THREAD

**Issue by GinesGarcia** [lagopus/lagopus#142]
Hi,
I'm trying set up a controller for GTP-U traffic but when running ``ryu-manager tunnel_gtpu.py`` I'm facing with the following error:
``TunnelGTPU: Exception occurred during handler processing. Backtrace from offending handler [switch_features_handler] servicing event [EventOFPSwitchFeatures] follows.
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/ryu/base/app_manager.py", line 290, in _event_loop
    handler(ev)
  File "/home/user/ryu-lagopus-ext/ryu/app/tunnel_gtpu.py", line 21, in switch_features_handler
    type_eth  = (ofp.OFPHTN_ONF << 16) | ofp.OFPHTO_ETHERNET
AttributeError: 'module' object has no attribute 'OFPHTN_ONF'``

``OFPHTN_ONF`` is defined in ofproto_v1_5.py but this controller is using ofproto_v1_3.py. If I force the controller to use ofproto_v1_5 instead of ofproto_v1_3, there are no compatible versions between them:
``
no compatible version found: switch versions set([4]) controller version 0x6, the negotiated version is 0x4, but no usable version found. If possi
ble, set the switch to use one of OF version [6] on datapath ('127.0.0.1', 46702)
``

Any suggestion about how to handle this situation?

Regards,
Ginés.

**Comment by GinesGarcia** [comment]
Ok, I've finally solve the issue. Althought in the readme of [https://github.com/lagopus/ryu-lagopus-ext](ryu-ext) the option of installing ryu via pip is proposed,  you must to install it by using the setup.py file in order to have all the extended files correctly loaded.
